function[SINR]=SINR_calculation(Power_Received,Interference,Noice)
Power_Received_watt=10^(Power_Received/10)/1000;
Interference_watt=10^(Interference/10)/1000;
Noice_watt=10^(Noice/10)/1000;
SINR_watt=Power_Received_watt/(Interference_watt+Noice_watt);
SINR=10*log10(SINR_watt*10^3);
%SINR=transmit_power_from_Macro/transmit_power_from_Femto+N
%SINR=10*log10(SINR1)
end
